$\textbf{Eigenvalues and Eigenvectors an Introduction}$

Definition: Let $A$ be an $n\times n$ matrix. Then , a scalar $\lambda$ is called an eigenvalue of \(A\) if
$$A\mathbf{x} = \lambda \mathbf{x} \mbox{ for some column vector } \mathbf{x} \neq \mathbf{0} \mbox{ in } \mathbb{C}^n \nonumber$$

In this case, $\mathbf{x}$ is called an eigenvector of $A$ corresponding to the eigenvalue $\lambda$, or a $\lambda $-eigenvector for short.

In [54]:

import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la


In [55]:
A = np.array([[-1,0],[0,1]])
evals,evecs = la.eig(A)

In [56]:
evals


array([-1.+0.j,  1.+0.j])

In [57]:
evecs


array([[1., 0.],
       [0., 1.]])

 $\textbf{ Problem 1 :}$ Consider the matrix $B=\left[\begin{array}{cc} 3&5 \\ 1&-1\end{array}\right],$ and   the vector $x=\left[\begin{array}{c}5 \\1 \end{array}\right].$ Is $x$ an eigenvector, if so find the corresponding eigenvalue of $B$ for the eigenvector $x.$

In [58]:
#"Test for eigenvalues and eigenvectors using the definition"
B = np.array([[3,5],[1,-1]])
x=np.array([5,1])
Bx=np.dot(B,x)
print(Bx)

[20  4]


Can you find $\lambda$ such that $Bx=\lambda x$?


In [96]:
Bx[0]/x[0]
Bx[1]/x[1]
print(Bx[0]/x[0])
print(Bx[1]/x[1])
if ( x[0] != 0 and x[1] != 0 and Bx[0] / x[0] == Bx[1] / x[1]): lambda_value1 = Bx[0] / x[0] 
else:
    lambda_value1 = None 
    
print("eigenvalue=" +str(lambda_value1))

4.0
4.0
eigenvalue=4.0


What happens if any of the entries of $x$ is zero?
Remember we are checking to see if the vectors $x$ and $Bx$ are parallel.

In [60]:
#  Check x is an eigenvector or not.
#Enter your response as True or False and save it as  result1.
# YOUR CODE HERE
result1 = True



In [61]:
# Test 1: Check if the result1 is True or False. (1 mark)
assert result1 ==True, "result should be  True."

print("Problem 1 Test 1: Success!")

Problem 1 Test 1: Success!


In [62]:
# Find the eigenvalue, if it exists.
#if eigenvalue_exists: value1 = computed_eigenvalue  # Replace with actual value else: value1 = "NA".
# YOUR CODE HERE
value1 =4

In [63]:
# Test 2: eigenvalue (1 mark)

assert value1==4 , "The eigenvalue is 4."

print("Problem 1 Test 2: Success!")

Problem 1 Test 2: Success!


$\textbf{ Problem 2:}$ Consider the matrix $B=\left[\begin{array}{cc} 3&5 \\ 1&-1\end{array}\right],$ and   the vector $y=\left[\begin{array}{c}3 \\2 \end{array}\right].$ 
 Is $y$ an eigenvector, if so find the corresponding eigenvalue of $B$ for the eigenvector $y.$

In [93]:
B = np.array([[3,5],[1,-1]])
y=np.array([3,2])
By=np.dot(B,y)
print(By)

[19  1]


Can you find a scalar $\lambda_2$ such that $By=\lambda_2 y$?


In [95]:
By[0]/y[0]
By[1]/y[1]
print(By[0]/y[0])
print(By[1]/y[1])
if ( y[0] != 0 and y[1] != 0 and By[0] / y[0] == By[1] / y[1]): lambda_value2 = By[0] / y[0] 
else:
    lambda_value2 = None 
    
print("eigenvalue=" +str(lambda_value2))

6.333333333333333
0.5
eigenvalue=None


In [66]:
#  Check x is an eigenvector or not.
#Enter your response as True or False and save it as  result2.
# YOUR CODE HERE
result2 = False

In [67]:
# Find the eigenvalue, if it exists.
#if eigenvalue_exists: value 2= computed_eigenvalue  # Replace with actual value else: value2 = "NA"
# YOUR CODE HERE
value2 ="NA"

In [68]:
# Test 2: eigenvalue (1 mark)

assert value2 =="NA"

print("Problem 2 Test 2: Success!")

Problem 2 Test 2: Success!


 $\textbf{ Problem 3:}$ Consider the matrix $C=\left[\begin{array}{ccc} 2&-1 &-1\\ -1&2&-1\\-1&-1&2\end{array}\right],$ and the vector $z=\left[\begin{array}{c}1 \\1\\1 \end{array}\right].$ Is $z$ an eigenvector, if so find the corresponding eigenvalue of $C$ for the eigenvector $z.$

In [70]:
C = np.array([[2,-1,-1],[-1,2,-1],[-1,-1,2]])
z=np.array([1,1,1])
Cz=np.dot(C,z)
w=print(Cz)

[0 0 0]


Can you find a scalar $\lambda_3$ such that $Cz=\lambda_3 z$?

In [100]:
Cz[0]/z[0]
Cz[1]/z[1]
Cz[2]/z[2]
print(Cz[0]/z[0])
print(Cz[1]/z[1])
print(Cz[2]/z[2])

if ( z[0] != 0 and z[1] != 0 and z[2] !=0 and Cz[0] / z[0] == Cz[1] / z[1]==  Cz[2] / z[2]): lambda_value3 =  Cz[1] / z[1] 
else:
    lambda_value3 = None 
    
print("eigenvalue=" +str(lambda_value3))

0.0
0.0
0.0
eigenvalue=0.0


In [72]:
#  Check x is an eigenvector or not.
#Enter your response as True or False and save it as  result3.
# YOUR CODE HERE
result3 = True

In [73]:
# Find the eigenvalue, if it exists.
#if eigenvalue_exists: value3= computed_eigenvalue  # Replace with actual value else: value3 = "NA"
# YOUR CODE HERE
value3 = 0

In [74]:
# Test 2: eigenvalue (1 mark)

assert value3==0, "The eigenvalue is 0."

print("Problem 3 Test 2: Success!")

Problem 3 Test 2: Success!
