Eigenvalues and Eigenvectors an Introduction

In [12]:

import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la


In [6]:
A = np.array([[-1,0],[0,1]])
evals,evecs = la.eig(A)

In [9]:
evals


array([-1.+0.j,  1.+0.j])

In [8]:
evecs


array([[1., 0.],
       [0., 1.]])

 Problem 1 : Consider the matrix $B=\left[\begin{array}{cc} 3&5 \\ 1&-1\end{array}\right],$ and   the vector $x=\left[\begin{array}{c}5 \\1 \end{array}\right].$ Is $x$ an eigenvector, if so find the corresponding eigenvalue of $B$ for the eigenvector $x.$

In [24]:
#"Test for eigenvalues and eigenvectors using the definition"
B = np.array([[3,5],[1,-1]])
x=np.array([5,1])
Bx=np.dot(B,x)
print(Bx)

[20  4]


Can you find $\lambda$ such that $Bx=\lambda x$?


In [34]:
#  Check x is an eigenvector or not.
#Enter your response as True or False and save it as  result.
# YOUR CODE HERE
result = True



In [35]:
# Test 1: Check if result is True or False. (1 mark)
assert result==True , "observation3a should be either True or False."

print("Problem 1 Test 1: Success!")

Problem 1 Test 1: Success!


Problem 2: Consider the matrix $B=\left[\begin{array}{cc} 3&5 \\ 1&-1\end{array}\right],$ and   the vector $y=\left[\begin{array}{c}3 \\2 \end{array}\right].$ 
 Is $y$ an eigenvector, if so find the corresponding eigenvalue of $B$ for the eigenvector $y.$

In [25]:
B = np.array([[3,5],[1,-1]])
y=np.array([3,2])
By=np.dot(B,y)
print(By)

[19  1]


Can you find a scalar $\lambda_2$ such that $By=\lambda_2 y$?


 Problem 3 : Consider the matrix $C=\left[\begin{array}{ccc} 2&-1 &-1\\ -1&2&-1\\-1&-1&2\end{array}\right],$ and the vector $z=\left[\begin{array}{c}1 \\1\\1 \end{array}\right].$ Is $z$ an eigenvector, if so find the corresponding eigenvalue of $C$ for the eigenvector $z.$

In [26]:
C = np.array([[2,-1,-1],[-1,2,-1],[-1,-1,2]])
z=np.array([1,1,1])
Cz=np.dot(C,z)
w=print(Cz)

[0 0 0]


Can you find a scalar $\lambda_3$ such that $Cz=\lambda_3 z$?